---
name: Rebase Upstream
on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: "30 1 * * *"  # run nightly
  workflow_dispatch:  # run manually

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - uses: imba-tjd/rebase-upstream-action@0.5
        with:
          upstream: vyos/vyos-1x
          branch: sagitta
