---
name: Rebase Upstream
on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: "10 * * * *"  # run hourly
  workflow_dispatch:  # run manually

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@current
        with:
          fetch-depth: 100
      - uses: imba-tjd/rebase-upstream-action@0.5
        with:
          upstream: vyos/vyos-1x
          branch: current
